[build.environment]
	NPM_FLAGS = "--force"

[build]
	publish = "packages/client/dist"
	command = "npx pnpm run build:client"

[functions]
	directory = "packages/server/functions"

# [[redirects]]
# 	from = "/*"
# 	to = "/index.html"
# 	status = 200
