[build.environment]
	NODE_VERSION = "14"

[build]
	publish = "packages/client/dist"
	command = "npx pnpm run build:client"
	functions = "packages/server/functions"

[functions]
	directory = "packages/server/functions"

# [[redirects]]
# 	from = "/*"
# 	to = "/index.html"
# 	status = 200
