[build.environment]
	NODE_VERSION = "14"

[build]
	publish = "packages/client/dist"
	command = "npx pnpm run build:client"

[functions]
	directory = "packages/server/functions"
	included_files = ["packages/server/fonts/*.woff"]

# [[redirects]]
# 	from = "/*"
# 	to = "/index.html"
# 	status = 200
